Update fill-thirst-mana-bar.md
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:12:35 WARN]: [ItemsAdder] Task #973 for ItemsAdder v4.0.11 generated an exception
java.lang.NullPointerException: Cannot invoke "itemsadder.m.cx.getWidth()" because "this.mv" is null
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dc.fd(SourceFile:213) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fK(SourceFile:109) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fJ(SourceFile:97) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fL(SourceFile:116) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.du.O(SourceFile:267) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.du.fH(SourceFile:162) ~[ItemsAdder_4.0.11 (1).jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
even with huds:
  thirst_bar:
    enabled: false
twinky
[BEER]
 — 2:17 AM
Look inside of contents/iasurvival and just delete the thirst stuff
bug
[FISH]

OP
 — 2:17 AM
I did thats what caused the error
even with everything gone it was still being weird
twinky
[BEER]
 — 2:18 AM
Remove storage folder
Do iacleancache items
Then do iazip again
bug
[FISH]

OP
 — 2:19 AM
ok so delete from contents\iasurvival\configs\thirst then Do iacleancache items
iazip
twinky
[BEER]
 — 2:19 AM
Yea
It's important you remove the configs too
They are mostly in iasurvival I believe
So you may need to look around a little
bug
[FISH]

OP
 — 2:21 AM
I dont mind keeping these items 

  thirst:
    enabled: false
    skip_if_already: false
    icon: iasurvival:cola
    name: display-category-thirst
    permission: ia.menu.seecategory.thirst
    items:
      
iasurvival:cola
iasurvival:hot_chocolate
iasurvival:coffee
iasurvival:bloody_mary
iasurvival:waterskin
iasurvival:boiled_water_bucket
iasurvival:empty_cup
iasurvival:cup_of_water
iasurvival:cup_of_hot_water

\I just want the hud to be gone, Im not sure what you mean by configs
\configs\thirst 
and texture\thirst
these^
twinky
[BEER]
 — 2:21 AM
There's a config specifically for the hud
Or a folder in iasurvival
bug
[FISH]

OP
 — 2:22 AM
the hud_thirst
twinky
[BEER]
 — 2:22 AM
Also some of those items do have functionality for the thirst player stat so idk it may break
twinky
[BEER]
 — 2:22 AM
Yes
bug
[FISH]

OP
 — 2:22 AM
yeah that was already gone
twinky
[BEER]
 — 2:23 AM
Whats happening?
bug
[FISH]

OP
 — 2:23 AM
1 sec
when i delete the thirst_bar foldeer from 
contents\iasurvival\resourcepack\iasurvival\textures\hud
an error shows up in console every tick
even when theres no configs for it
twinky
[BEER]
 — 2:26 AM
Yea im gonna assume it's because something is trying to increment or decrement the thirst but it's failing
Somewhere there is for sure some items or things that are causing it.

I recommend you remove everything in contents and slowly start reading stuff till it occurs again
So you know where the issue is
Folder by folder
bug
[FISH]

OP
 — 2:30 AM
its just spamming it 

thats kinda boonk tho, id reather not add all the ia folders 1by 1 bc I still dont think ill even find the issue

the wiki just says 

Disable thirst
open contents/iasurvival/configs/thirst/hud_thirst.yml

set enabled: false

use /iareload command

and it should be fine,

but the texture still stays even with it dissabled. is there any way you guys could look at it because ive seen a couple users report the thurst
[23:26:07 WARN]: [ItemsAdder] Task #21865 for ItemsAdder v4.0.11 generated an exception
java.lang.NullPointerException: Cannot invoke "itemsadder.m.cx.getWidth()" because "this.mv" is null
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dc.fd(SourceFile:213) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fK(SourceFile:109) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fJ(SourceFile:97) ~[ItemsAdder_4.0.11 (1).jar:?]
        at ItemsAdder_4.0.11 (1).jar/itemsadder.m.dx.fL(SourceFile:116) ~[ItemsAdder_4.0.11 (1).jar:?]
Expand
message.txt
17 KB
twinky
[BEER]
 — 2:32 AM
Well idk looking at the error I still think it's just other items causing it, can you atleast remove iasurvival just for testing purposes
But yea if we can't fix it we will bring it to lonedev
bug
[FISH]

OP
 — 2:33 AM
alr. ima be going on vacation, so ill try it in a few days, thanks for the help 🙂 
twinky
[BEER]
 — 2:34 AM
Enjoy!
bug
[FISH]

OP
 — 2:41 AM
I think I mighta foud a fix that disables it  from the hud i say a post from lone dev 

you have to disable the HUDs in config.yml.

doing this 
huds:
  enabled: false
  force_color:
    enabled: false
    color: '#FFFFFF'

this fixed it but Im sure that that will cause issues for huds in the future because I plan to add a fishing hud. we shall see tho
plugins\ItemsAdder|config.yml